### ISSUE TITLE
Siteorigin Template

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/naturelle#59]
@rodica-andronache could we add one for Naturelle? If you use the current template with Siteorigin on Naturelle it will look like siteorigin is simply overlaying

**Comment by suyogyashukla** [comment]
+ 1

**Comment by suyogyashukla** [comment]
+1

**Comment by rodica-andronache** [comment]
@UVLabs @suyogyashukla can you please give more details here? Isn't the "Full Width with no title template" template from the parent theme usable? Is there any difference if that template is used in the parent theme and in this child theme?
I'm asking because it's not ideal to update the child theme
